export const links_artists = [
    { name: "5SING", icon: null, background: null }, // linear-gradient
    { name: "Apple Music", icon: '<i class="bi bi-apple-music"></i>', background: '#ff0436' },
    { name: "Audiostock", icon: null, background: '#ff0000' },
    { name: "Booth", icon: null, background: '#fc4d50' },
    { name: "Bandcamp", icon: null, background: '#629aa9' },
    { name: "Bilibili", icon: null, background: '#66CCFF' },
    { name: "Blog", icon: '<i class="bi bi-globe-americas-fill"></i>', background: null },
    { name: "Blogspot", icon: null, background: '#F57D00' },
    { name: "Bluesky", icon: null, background: '#F57D00' },
    { name: "Bowlroll", icon: null, background: '#0000001a', color: '#777' },
    { name: "Creofuga", icon: null, background: '#00C2FF' }, 
    { name: "DeviantArt", icon: null, background: '#05cc47', color: 'black' },
    { name: "Facebook", icon: '<i class="bi bi-facebook"></i>', background: '#1e85ff' },
    { name: "Instagram", icon: null, background: null }, // linear-gradient
    { name: "LINE", icon: null, background: '#06C755' },
    { name: "Linktree", icon: null, background: '#C19BFF' },
    { name: "Lit.link", icon: null, background: '#9494f9' },
    { name: "MQube", icon: null, background: '#222' },
    { name: "MySpace", icon: null, background: '#0e1079' },
    { name: "NND Account", icon: null, background: 'white', color: 'gray' },
    { name: "NND Community", icon: null, background: 'white', color: 'gray' },
    { name: "NND MyList", icon: null, background: 'white', color: 'gray' },
    { name: "Nana", icon: null, background: '#e41f74', color: 'gray' },
    { name: "NicoNicoDouga", icon: null, background: 'white' },
    { name: "NicoNicoSeiga", icon: null, background: 'white', color: 'gray' },
    { name: "Nicommons", icon: null, background: 'white', color: 'gray' },
    { name: "Note", icon: null, background: 'white', color: 'black' },
    { name: "ONLINE SHOP", icon: null, background: null },
    { name: "Official Shop", icon: null, background: null },
    { name: "Otaku Republic", icon: null, background: '#ff9900' },
    { name: "Piapro", icon: null, background: '#f15587' },
    { name: "Pixiv", icon: null, background: '#0096FA' },
    { name: "SoundCloud", icon: '<i class="bi bi-cloud-fog2-fill"></i>', background: '#ff5500' },
    { name: "Spotify", icon: '<i class="bi bi-spotify"></i>', background: '#1DB954' },
    { name: "Steam", icon: '<i class="bi bi-steam"></i>', background: '#292e37' },
    { name: "Suruga-ya", icon: null, background: '#1d2088' },
    { name: "TMBOX", icon: null, background: 'black', color: '#F2C500' },
    { name: "Threads", icon: null, background: 'black' },
    { name: "TikTok", icon: '<i class="bi bi-tiktok"></i>', background: 'black' },
    { name: "Tumblr", icon: null, background: '#36465d' },
    { name: "TuneCore", icon: null, background: '#ff1212', color: 'black' },
    { name: "Twitch", icon: '<i class="bi bi-twitch"></i>', background: '#6441a5' },
    { name: "Twitter", icon: '<i class="bi bi-twitter"></i>', background: '#1DA1F2' },
    { name: "VOCALOTRACKS", icon: null, background: null },
    { name: "Website", icon: '<i class="bi bi-globe-americas-fill"></i>', background: null },
    { name: "YouTube Channel", icon: '<i class="bi bi-youtube"></i>', background: '#FF0000' },
    { name: "YouTube List", icon: '<i class="bi bi-youtube"></i>', background: '#FF0000' },
    { name: "YouTube Playlist", icon: '<i class="bi bi-youtube"></i>', background: '#FF0000' },
    { name: "YouTube", icon: '<i class="bi bi-youtube"></i>', background: '#FF0000' },
    { name: "iTunes", icon: '<i class="bi bi-apple"></i>', background: 'black' }
]