export const links = [
    { name: "#compass store", icon: null, background: null },
    { name: "1nfinity 0rchestra", icon: null, background: null },
    { name: "AWA", icon: null, background: 'black' },
    { name: "Akibaoo", icon: null, background: null },
    { name: "Alice Books", icon: null, background: null },
    { name: 'Amazon Music', icon: '<i class="bi bi-amazon" style="filter: invert(1);"></i>', background: '#0DBFF5', color: '#000000' },
    { name: 'Amazon MP3', icon: '<i class="bi bi-amazon" style="filter: invert(1);"></i>', background: '#0DBFF5', color: '#000000' },
    { name: "Amazon", icon: '<i class="bi bi-amazon"></i>', background: '#e47911' },
    { name: "AmiAmi", icon: null, background: '#f38029' },
    { name: "Animate Online Shop", icon: null, background: '#3663b3' },
    { name: "Apple Music", icon: '<i class="bi bi-apple-music"></i>', background: '#ff0436' },
    { name: "BIG UP!", icon: null, background: null },
    { name: "Bandcamp", icon: null, background: '#629aa9' },
    { name: "Bluesky", icon: null, background: null },
    { name: "Booth", icon: null, background: null },
    { name: "CDJapan", icon: null, background: '#09c' },
    { name: "Club ZION", icon: null, background: null },
    { name: "DE-LUXE", icon: null, background: null },
    { name: "Deexer", icon: null, background: null },
    { name: "Deezer", icon: '<i class="bi bi-bar-chart-line-fill"></i>', background: '#A238FF' },
    { name: "Exit Tunes", icon: null, background: null },
    { name: "Facio", icon: null, background: null },
    { name: "Fanlink.to", icon: null, background: null },
    { name: "Gynoid", icon: null, background: null },
    { name: "HACHIMAKI", icon: null, background: null },
    { name: "HMV&BOOKS", icon: null, background: null },
    { name: "KKBOX", icon: null, background: '#09CEF6' },
    { name: "KONAMI MUSIC", icon: null, background: null },
    { name: "KarenT", icon: null, background: 'white', color: 'black' },
    { name: "Kinokuniya", icon: null, background: null },
    { name: "Kugou", icon: null, background: null },
    { name: "Line Music", icon: '<i class="bi bi-music-note-beamed"></i>', background: '#06C755' },
    { name: "Loudr", icon: null, background: null },
    { name: "Media Factory", icon: null, background: null },
    { name: "Melonbooks", icon: null, background: '#3C8C3C' },
    { name: "Music Store", icon: null, background: null },
    { name: "MySound", icon: null, background: '#06C755', color: 'black' },
    { name: "NCM Album Release", icon: null, background: null },
    { name: "NND MyList", icon: null, background: null },
    { name: "Neowing", icon: null, background: null },
    { name: "Nico Booth", icon: null, background: null },
    { name: "Nico Nico Blog", icon: null, background: null },
    { name: "Note", icon: null, background: null },
    { name: "OTOTOY", icon: null, background: 'white', color: 'black' },
    { name: "ORICON", icon: null, background: 'blue' },
    { name: "Poly Vinyl Records", icon: null, background: null },
    { name: "Rakuten music", icon: null, background: null },
    { name: "Recochoku", icon: null, background: null },
    { name: "Reggae ZION", icon: null, background: null },
    { name: "SoundCloud", icon: '<i class="bi bi-cloud-fog2-fill"></i>', background: '#ff5500' },
    { name: "Spotify", icon: '<i class="bi bi-spotify"></i>', background: '#1DB954' },
    { name: "Storenvy", icon: null, background: null },
    { name: "Stripeless", icon: null, background: null },
    { name: "Suruga-ya", icon: null, background: null },
    { name: "TIDAL", icon: null, background: null },
    { name: "TSUTAYA", icon: null, background: '#252440' },
    { name: "Taobao", icon: null, background: null },
    { name: "Tokyo Otaku Mode", icon: null, background: null },
    { name: "Toranoana", icon: null, background: '#ffc107', color: 'black' },
    { name: "Tower", icon: null, background: '#fdd000', color: '#d6000f' },
    { name: "TuneCore", icon: null, background: null },
    { name: "UMAA", icon: null, background: null },
    { name: "Village Vanguard", icon: null, background: null },
    { name: "Yoshimoto Kogyo", icon: null, background: null },
    { name: "YouTube Music", icon: '<i class="bi bi-play-circle"></i>', background: '#FF0000' },
    { name: "YouTube", icon: '<i class="bi bi-youtube"></i>', background: '#FF0000' },
    { name: "animelo mix", icon: null, background: null },
    { name: "docomo", icon: null, background: null },
    { name: "dwango.jp", icon: null, background: null },
    { name: "iTunes", icon: '<i class="bi bi-apple"></i>', background: 'black' },
    { name: "mora", icon: null, background: '#252440' },
    { name: "mu-mo", icon: null, background: null },
    { name: "music.jp", icon: null, background: null },
    { name: "musicstore.auone", icon: null, background: null },
    { name: "nodee", icon: null, background: '#81A0C1' },
    { name: "recochoku", icon: null, background: null },
    { name: "tf.lnk.to", icon: null, background: null }
];
